server:
  port: 8090
gateway:
  uri: http://localhost:8000
domain:
  product:
    mapping: "/product"
    enabled: true
  producthistory:
    mapping: "/producthistory"
    enabled: true
  recommendation:
    mapping: "/recommendation"
    enabled: true
  needsanalysis:
    mapping: "/needsanalysis"
    enabled: true
---

spring:
  profiles: env1
domain:
  employee:
    enabled: false
  product:
    enabled: false
---

spring:
  profiles: env2
domain:
  employee:
    enabled: true
  product:
    enabled: false
---

spring:
  profiles: default
domain:
  product:
    enabled: true
  recommendation:
    enabled: true
